name = "purple-shadow-79eb"
main = "index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "BOT_DB"
database_name = "bot_data"
database_id = "4b01d685-7046-4e18-b2b8-ca4881e2dc7a"

[[kv_namespaces]]
binding = "BOT_KV"
id = "7f5b66b9b406467194e89f4c9f013597"
